version: '3.1'

services:
  db:
    container_name: mariadb_testdatabase
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
    networks:
      - test-environment

networks:
  test-environment:
